name: CI - Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore netcore/exploringactions/exploringactions.sln

      - name: Build the solution
        run: dotnet build netcore/exploringactions/exploringactions.sln --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test netcore/exploringactions/testexploringapi/testexploringapi.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: netcore/exploringactions/testexploringapi/TestResults/TestResults.trx
          
